/* Sprachen / Languages */
'use strict';
HK.LANG = 'de';
HK.I18N = {
  de: {
    title: 'Hanse-Kontor', subtitle: 'Sundhaven, anno 1372. Eine kleine Hansestadt, ein Hafen, und dein Weg zur Macht.',
    newGame: 'Neues Spiel', continueGame: 'Spiel fortsetzen', continuePlay: 'Weiterspielen', save: 'Speichern', load: 'Laden', exportSave: 'Exportieren', importSave: 'Importieren',
    help: 'Hilfe', saved: 'Spielstand gespeichert.', loaded: 'Spielstand geladen.', noSave: 'Kein Spielstand vorhanden.', importError: 'Die Datei konnte nicht gelesen werden.',
    confirmNewGame: 'Aktuelles Spiel verwerfen und neu beginnen?', playerName: 'Dein Name', difficulty: 'Schwierigkeit', easy: 'Leicht', normal: 'Normal', hard: 'Schwer', defaultName: 'Hinrich Castorp',
    diffHint_easy: '12.000 Mark, ruhige Zeiten, viele Schiffe.', diffHint_normal: '6.000 Mark.', diffHint_hard: '3.000 Mark, raue Zeiten, wenige Schiffe.',
    day: 'Tag', money: 'Kasse', rank: 'Rang', pause: 'Pause', speed1: 'Langsam', speed2: 'Normal', speed3: 'Schnell', stepDay: 'Einen Tag weiter', mark: 'Mark', unitLast: 'Last',
    rep: 'Ruf', influence: 'Einfluss', piety: 'Frömmigkeit', suspicion: 'Verdacht', prosperity: 'Wohlstand', population: 'Einwohner', netWorth: 'Reinvermögen',
    tabOverview: 'Übersicht', tabLog: 'Chronik', tabHelp: 'Hilfe', back: 'Zurück', close: 'Schließen', cancel: 'Abbrechen', ok: 'OK', yes: 'Ja', no: 'Nein', none: 'keins',
    shortage: 'Mangel', surplus: 'Überschuss', normalDemand: 'gedeckt', good: 'Ware', qty: 'Menge', price: 'Preis', stock: 'Vorrat', buy: 'Kaufen', sell: 'Verkaufen', max: 'Max',
    warehouse: 'Lager', warehouseCap: 'Lagerplatz', capacityHint: '{used} / {cap} Last', expandWarehouse: 'Lager erweitern (+{qty} Last, {cost} Mark)', empty: 'leer',
    notEnoughStock: 'Nicht genug Vorrat.', warehouseFull: 'Das Lager ist voll.', notEnoughMoney: 'Nicht genug Geld.', notWanted: 'So viel wird nicht gesucht.', notEnoughCargo: 'Nicht genug im Lager.',
    monopolyBlocked: 'Ein Konkurrent hält das Monopol auf diese Ware.', marketSaturated: 'Mehr nehmen die Bürger heute nicht ab.', marketCapHint: 'heute noch', pietyTooLow: 'Die Kirche handelt nur mit frommen Kaufleuten (Frömmigkeit 40).', needLoyalty: 'Dafür müsste er dir wohlgesonnener sein.',
    needInfluence: 'Du brauchst 20 Einfluss für einen Antrag.', needRep: 'Dein Ruf reicht dafür nicht.', needGuild: 'Nur Gildemitglieder erhalten Lizenzen.', needLicense: 'Dafür fehlt die Gildelizenz.',
    loanTooHigh: 'Der Kreditrahmen reicht nicht.', maxShips: 'Mehr als drei Schiffe kann der Hafen nicht aufnehmen.', shipDamaged: 'Das Schiff muss erst repariert werden.', shipFull: 'Das Schiff ist voll (120 Last).',
    /* Hafen */
    harbour: 'Hafen', shipsInPort: 'Schiffe im Hafen', noShips: 'Zurzeit liegt kein fremdes Schiff im Hafen.', fromOrigin: 'aus {origin}', captain: 'Kapitän', leavesIn: 'legt in {days} Tagen ab',
    offers: 'Bietet an', wants: 'Sucht', tariffInfo: 'Zoll: {rate} % (dein Nachlass durch den Zöllner: {disc} %)', smuggle: 'Nachts schmuggeln (ohne Zoll)', smuggleHint: 'Ohne Zoll, aber der Zöllner könnte dich erwischen.',
    bought: '{qty} Last {good} für {cost} Mark gekauft.', sold: '{qty} Last {good} für {cost} Mark verkauft.', smuggledOk: 'Geschmuggelt, {saved} Mark Zoll gespart.',
    ownShips: 'Deine Schiffe', noOwnShips: 'Du besitzt kein Schiff. Die Werft baut dir eines.', inPort: 'im Hafen', away: 'unterwegs nach {dest}, zurück in {days} Tagen', cargo: 'Ladung',
    loadShip: 'Laden', unloadShip: 'Löschen', sendShip: 'Auf Fahrt schicken', destination: 'Ziel', bringBack: 'Rückfracht', expeditionHint: 'Das Schiff verkauft seine Ladung am Ziel (gesuchte Waren bringen bis zum 1,5-fachen Grundpreis) und kauft mit dem Erlös die Rückfracht günstig ein.',
    daysTrip: '{days} Tage Fahrt', repairShip: 'Reparieren ({cost} Mark)', sellShip: 'Verkaufen ({price} Mark)', hull: 'Zustand',
    /* Markt */
    market: 'Marktplatz', marketHint: 'Hier verkaufst du an die Bürger und kaufst, was die Stadt erzeugt. Die Bürger nehmen täglich nur begrenzte Mengen ab; Marktstände erhöhen Absatz und Preis. Marktgebühr: {fee} %.', stalls: 'Marktstände', buyStall: 'Stand pachten ({cost} Mark, +4 % Preis, +50 % Absatz)',
    monopolyYours: 'Du hältst das Monopol auf {good} (+35 % Preis).', demand: 'Bedarf', buyPrice: 'Kauf', sellPrice: 'Verkauf',
    /* Kontor */
    kontor: 'Kontor', ledger: 'Kassenbuch (letzte 30 Tage)', income: 'Einnahmen', expenses: 'Ausgaben', balance: 'Saldo', assets: 'Besitz',
    src_shipTrade: 'Schiffs- & Karawanenhandel', src_market: 'Markthandel', src_tariffs: 'Zölle', src_rent: 'Mieten', src_tavern: 'Taverne', src_bathhouse: 'Badehaus', src_lending: 'Geldverleih', src_expedition: 'Handelsfahrten',
    src_taxFarm: 'Zollpacht', src_office: 'Amt', src_gambling: 'Glücksspiel', src_church: 'Kirche & Almosen', src_wages: 'Löhne', src_interest: 'Zinsen', src_bribes: 'Geschenke & Bestechung', src_fines: 'Strafen',
    src_investments: 'Käufe & Bauten', src_politics: 'Politik', src_loans: 'Darlehen',
    /* Rathaus */
    townhall: 'Rathaus', council: 'Der Rat', yourSeat: 'Dein Sitz', seat_none: 'kein Sitz', seat_councillor: 'Ratsherr', seat_mayor: 'Bürgermeister', loyalty: 'Wohlwollen', faction: 'Fraktion',
    giveGift: 'Geschenk ({cost} Mark)', giftDone: '{name} nimmt dein Geschenk wohlwollend an.', laws: 'Gesetze', current: 'derzeit', propose: 'Antrag stellen (20 Einfluss)',
    motionPassed: 'Antrag angenommen: {law} → {value} ({yes}:{no}).', motionFailed: 'Antrag abgelehnt: {law} → {value} ({yes}:{no}).', lawHint_tariff: 'Niedriger Zoll macht deinen Schiffshandel billiger; hoher Zoll füllt die Zollpacht.',
    lawHint_marketFee: 'Wird von jedem Marktverkauf abgezogen.', lawHint_usuryBan: 'Geldverleih wird verdächtig, wenn das Verbot gilt.', lawHint_staple: 'Mehr Schiffe laufen den Hafen an.',
    lawHint_bathBan: 'Schließt das Badehaus.', lawHint_monopoly: 'Nur der Monopolinhaber darf diese Ware verkaufen – zum Aufpreis.',
    runCouncillor: 'Um einen Ratssitz bewerben (3.000 Mark, Ruf 35, drei wohlgesonnene Ratsherren)', runMayor: 'Zum Bürgermeister kandidieren (6.000 Mark, Ruf 55, vier wohlgesonnene Ratsherren)',
    becameCouncillor: 'Du sitzt nun im Rat von Sundhaven.', becameMayor: 'Du bist Bürgermeister von Sundhaven!', electionLost: 'Die Wahl ging verloren: nur {support} von {need} Ratsherren stimmten für dich.',
    acceptBribes: 'Als Amtsträger Bestechungsgelder annehmen (+Geld, +Verdacht)', projects: 'Städtische Vorhaben', fund: 'Stiften ({cost} Mark)', funded: 'gestiftet', projectDone: '{project} vollendet.',
    taxFarm: 'Zollpacht', taxFarmHint: 'Kaufe das Recht, ein Jahr lang alle Hafenzölle einzunehmen.', buyTaxFarm: 'Zollpacht erwerben ({cost} Mark)', taxFarmActive: 'Du hältst die Zollpacht noch {days} Tage.',
    taxFarmBought: 'Du hast die Zollpacht für {days} Tage erworben.', taxFarmEnded: 'Deine Zollpacht ist abgelaufen.', bathClosed: 'Das Badehausverbot schließt dein Badehaus.',
    levy: 'Der Rat verlangt eine Abgabe von {amount} Mark (noch {days} Tage).', payLevy: 'Abgabe zahlen', levyDemand: 'Der Rat erhebt eine Sonderabgabe von {amount} Mark.', levyIgnored: 'Du hast die Abgabe nicht gezahlt. Dein Ruf leidet.',
    /* Kirche */
    church: 'Kirche St. Nikolai', churchHint: 'Frömmigkeit öffnet Türen: die Kirche kauft Wachs und Wein, der Bischof lobt dich, und Ablässe tilgen Verdacht.',
    donate: 'Spenden', donateAmount: 'Spende ({amount} Mark)', indulgence: 'Ablass kaufen ({cost} Mark, −20 Verdacht)', churchSupply: 'Die Kirche braucht diese Woche', supply: 'Liefern ({qty} Last, {price} Mark/Last)',
    churchProjects: 'Stiftungen', sermonFavor: 'Predigt zu deinen Gunsten (500 Mark, +8 Ruf)', sermonAgainst: 'Predigt gegen einen Konkurrenten (800 Mark)',
    sermonAgainstLog: 'Pater Anselm predigt gegen {rival}.', bishopPleased: 'Der Bischof besucht Sundhaven und lobt deine Frömmigkeit.', bishopDispleased: 'Der Bischof besucht Sundhaven und rügt deinen Lebenswandel.',
    /* Zoll */
    customs: 'Zollhaus', customsHint: 'Der Zöllner {name} erhebt {rate} % Zoll auf Einfuhren und die Hälfte auf Ausfuhren. Je mehr er dich mag, desto mehr drückt er ein Auge zu (derzeit {disc} % Nachlass).',
    smuggleStats: 'Bisher am Zoll vorbeigeschmuggelt: {amount} Mark.', smuggleCaught: 'Beim Schmuggeln erwischt! Strafe: {fine} Mark.',
    /* Gilde */
    guild: 'Gildehaus', guildHint: 'Die Gilde vergibt Lizenzen für Werkstätten. Mitgliedschaft: {fee} Mark.', joinGuild: 'Der Gilde beitreten ({fee} Mark)', member: 'Mitglied', licenses: 'Lizenzen', buyLicense: 'Lizenz ({cost} Mark)', licensed: 'lizenziert',
    /* Werkstatt */
    workshop: 'Werkstatt', workshopEmpty: 'Unbebautes Grundstück. Mit Gildelizenz kannst du hier einen Betrieb errichten.', build: 'Bauen ({cost} Mark)', produces: 'erzeugt {qty} Last {good}/Tag', consumes: 'verbraucht {inp}',
    wage: 'Löhne {wage} Mark/Tag', idle: 'steht still – Rohstoffe fehlen im Lager', running: 'in Betrieb', demolish: 'Abreißen', workshopBuilt: '{workshop} errichtet.',
    /* Haus */
    house: 'Wohnhaus', houseOwnerNpc: 'Im Besitz eines Bürgers. Kaufpreis: {price} Mark.', buyHouse: 'Kaufen ({price} Mark)', rentPerDay: 'Miete {rent} Mark/Tag', level: 'Ausbaustufe {level}',
    upgradeHouse: 'Ausbauen ({cost} Mark, +12 Mark/Tag)', sellHouse: 'Verkaufen ({price} Mark)', damaged: 'Brandschaden – keine Miete', repairHouse: 'Reparieren (800 Mark)', yours: 'Dein Besitz',
    /* Taverne */
    tavern: 'Taverne „Zum Goldenen Hering“', tavernHint: 'Hier gibt es Gerüchte, Würfel und Leute, die für Geld alles tun.', rumor: 'Gerücht kaufen ({cost} Mark)', rumors: 'Was man so hört',
    rumorShip: 'Ein Schiff aus {origin} soll in {days} Tagen einlaufen, mit {goods}.', rumorCaravan: 'Eine Karawane aus {origin} wird in {days} Tagen erwartet, mit {goods}.', rumorNothing: 'Nichts Neues – nur Klatsch über den Bürgermeister.',
    gamble: 'Würfeln', bet: 'Einsatz', gambleWon: 'Gewonnen! {bet} Mark dazu.', gambleLost: 'Verloren. {bet} Mark weg.', hire: 'Anheuern', hireSpy: 'Spitzel (600 Mark, 60 Tage): zeigt das wahre Wohlwollen des Rats',
    spyActive: 'Dein Spitzel berichtet noch {days} Tage.', hireThugsCollect: 'Schläger: säumigen Schuldner eintreiben ({cost} Mark)', hireThugsSabotage: 'Schläger: {rival} schaden ({cost} Mark)',
    thugsCollected: 'Die Schläger haben {amount} Mark von {name} eingetrieben.', thugsFailed: '{name} ist untergetaucht – die Schläger kamen mit leeren Händen.', thugsNothing: 'Es gibt keinen säumigen Schuldner.',
    sabotageOk: 'Ein Lagerbrand hat {rival} schwer getroffen.', sabotageFailed: 'Die Schläger wurden gefasst und haben dich verraten – {rival} weiß Bescheid.',
    buyTavern: 'Taverne kaufen ({cost} Mark)', tavernOwned: 'Deine Taverne bringt {income} Mark/Tag (mehr, wenn Schiffe im Hafen liegen).',
    /* Geldwechsler */
    bank: 'Geldwechsler', yourLoan: 'Dein Darlehen', loanLimit: 'Kreditrahmen', takeLoan: 'Aufnehmen', repay: 'Zurückzahlen', interestInfo: 'Zins {pct} % pro Jahr',
    lending: 'Geld verleihen', lendingHint: 'Bürger suchen Kredit. Hoher Zins heißt hohes Risiko. Bei geltendem Wucherverbot macht dich jedes Darlehen verdächtig.', lend: 'Verleihen',
    borrower: 'Schuldner', interest: 'Zins', term: 'Laufzeit {days} Tage', risk: 'Risiko', risk_low: 'gering', risk_mid: 'mittel', risk_high: 'hoch', outstanding: 'Laufende Darlehen', dueIn: 'fällig in {days} Tagen',
    defaulted: 'säumig', loanDefault: '{name} kann {amount} Mark nicht zurückzahlen.', loanRepaid: '{name} zahlt {amount} Mark zurück.', usuryWarning: 'Wucherverbot gilt!',
    /* Vogtei */
    bailiff: 'Vogtei', bailiffHint: 'Der Vogt {name} wacht über Recht und Ordnung. Bei hohem Verdacht ermittelt er; ab 85 kommt es zum Prozess.', noInvestigation: 'Gegen dich liegt nichts vor.',
    investigation: 'Der Vogt ermittelt gegen dich – noch {days} Tage bis zum Urteil.', bribeBailiff: 'Vogt bestechen ({cost} Mark)', investigationOpened: 'Der Vogt hat Ermittlungen gegen dich eröffnet.',
    investigationDropped: 'Die Ermittlungen wurden eingestellt.', bribeRefused: 'Der Vogt weist dein Geld zurück – und merkt es sich.', investigationFine: 'Der Vogt verurteilt dich zu {fine} Mark Strafe.',
    trial: 'Prozess vor dem Rat! {fine} Mark Strafe, Ämter verloren, Ruf ruiniert.',
    /* Werft, Fischer, Tor */
    shipyard: 'Werft', shipyardHint: 'Werftmeister {name} baut Koggen für Handelsfahrten und Fischerboote.', buyShip: 'Kogge bauen ({cost} Mark, 120 Last)', buyBoat: 'Fischerboot ({cost} Mark, {fish} Fisch/Tag)', boats: 'Fischerboote',
    fishermen: 'Fischerhütten', fishermenHint: 'Die Fischer verkaufen ihren Fang billig direkt vom Steg. Heute: {qty} Last zu {price} Mark.', buyFish: 'Fisch kaufen',
    gate: 'Stadttor', gateHint: 'Karawanen vom Landweg lagern vor dem Tor.', caravans: 'Karawanen', noCaravans: 'Vor dem Tor lagert zurzeit niemand.', caravanFrom: 'Karawane aus {origin}',
    /* Ereignisse */
    shipArrived: '{ship} aus {origin} ist eingelaufen.', caravanArrived: 'Eine Karawane aus {origin} hat das Tor erreicht.', shipLeftNoBerth: 'Ein Schiff aus {origin} fand keinen Liegeplatz und segelte weiter.',
    ev_famine: 'Hungersnot in Sundhaven! Getreide und Fisch sind gefragt.', ev_plague: 'Die Pest ist in der Stadt. Die Straßen leeren sich.', ev_goodCatch: 'Reicher Fang! Fisch ist billig.', ev_fair: 'Jahrmarkt in Sundhaven – Tuch, Pelze und Gewürze gefragt.',
    evn_famine: 'Hungersnot', evn_plague: 'Pest', evn_goodCatch: 'Reicher Fang', evn_fair: 'Jahrmarkt', fireHouse: 'Feuer! {house} ist ausgebrannt.', fireWarehouse: 'Feuer im Hafenviertel – ein Zehntel deines Lagers ist verbrannt.',
    piratesRepelled: 'Vitalienbrüder vor der Küste! Die Stadtmauer hält sie fern.', piratesRaid: 'Vitalienbrüder plündern den Hafen! Schiffe fliehen, Lager brennen.', stormEvent: 'Schwerer Sturm auf See. Schiffe verspäten sich.',
    expeditionPirates: '{ship} wurde von Piraten ausgeraubt.', shipSent: '{ship} segelt nach {dest}.', shipReturned: '{ship} ist zurück: {revenue} Mark Erlös, Rückfracht {cargo}.',
    season_lent: 'Fastenzeit', season_easter: 'Ostern', season_midsummer: 'Johannisfest', season_michaelmas: 'Michaelis', season_christmas: 'Weihnachten',
    promoted: 'Man nennt dich nun {rank}.', won: 'Du bist Bürgermeister, reichster Mann der Stadt und Herr von Sundhaven!', bankrupt: 'Du bist bankrott. Die Gläubiger übernehmen dein Kontor.', gameOver: 'Spiel vorbei',
    welcome: 'Willkommen in Sundhaven, {name}! Zwei Schiffe liegen im Hafen, eine Karawane vor dem Tor. Klicke auf Gebäude und Menschen.',
    /* Begegnungen */
    encBeggar: 'Ein Bettler streckt dir die Hand entgegen. „Ein Almosen, Herr, um Gottes willen.“', encMonk: 'Ein Bettelmönch bittet um eine Gabe für das Kloster.', alms: 'Geben ({cost} Mark)',
    encMerchantTip: 'Ein Kaufmann raunt: „{good}? Auf dem Markt herrscht {label}.“', encMerchant: 'Ein Kaufmann grüßt knapp und eilt zum Hafen.', encFisher: 'Ein Fischer bietet dir 10 Last Fisch unter der Hand an.', cheapFish: 'Nehmen ({cost} Mark)',
    encFisherTalk: 'Ein Fischer klagt über die Vitalienbrüder und die Preise für Salz.', encGuard: 'Die Stadtwache nickt dir zu.', encGuardSuspicious: 'Die Wache mustert dich lange. Man redet über dich.', encChild: 'Kinder spielen Fangen und rennen dir fast in die Beine.',
    encGossip: 'Eine Bürgerin tuschelt: Ratsherr {name} sei dir {loyalty}.', gossipFriendly: 'wohlgesonnen', gossipCold: 'nicht grün', encCitizenRep: 'Ein Bürger grüßt. Dein Ruf in der Stadt liegt bei {rep}.', encCitizen: 'Ein Bürger wünscht einen guten Tag.', bathhouse: 'Badehaus', buyBathhouse: 'Badehaus kaufen ({cost} Mark)', leader: 'Karawanenführer', movesOn: 'zieht in {days} Tagen weiter',
    enc_citizen_label: 'Bürger', enc_merchant_label: 'Kaufmann', enc_fisher_label: 'Fischer', enc_beggar_label: 'Bettler', enc_monk_label: 'Mönch', enc_guard_label: 'Stadtwache', enc_child_label: 'Kinder',
    /* Übersicht */
    overview: 'Übersicht', goals: 'Sechs Wege, sechs Titel: Handelsfürst, Bürgermeister, Reeder, Stifter, Ältermann oder Herr der Nacht. Am Ende der Spielzeit schreibt der Chronist deine Bilanz.', richest: 'Die Reichsten der Stadt', you: 'du', incomeSources: 'Deine Einnahmequellen',
    dailyIncome: 'Ø Tageseinnahmen', chart: 'Reinvermögen im Verlauf', noLog: 'Noch nichts geschehen.', activeEvents: 'Zurzeit in der Stadt', personsTitle: 'Wichtige Leute',
    legend: 'Klicke auf Gebäude, Schiffe, Karawanen und Passanten. Mausrad zoomt, Ziehen verschiebt die Karte.', timeOfDay: 'Tageszeit', night: 'Nacht', morning: 'Morgen', noon: 'Mittag', evening: 'Abend',
    /* Neue Viertel */
    needCraftGuild: 'Dafür musst du der Zunft angehören.', needThreeVentures: 'Der Meistertitel setzt drei eigene Betriebe voraus.', storageInUse: 'Der Speicher ist noch belegt – erst das Lager leeren.', fenceFull: 'Der Hehler nimmt heute nichts mehr ab.', noShipsHere: 'Es liegt kein fremdes Schiff im Hafen.',
    craftJoined: 'Die Zunft hat dich aufgenommen.', ventureBought: '{venture} gehört jetzt dir.', masterTitleLog: 'Die Zunft ernennt dich zum Ältermann.', relicDonated: 'Das Kloster stellt deine Reliquie im Chor auf. Ganz Sundhaven pilgert.', hospitalEndowedLog: 'Du bist Stifter des Heilig-Geist-Spitals.', schoolEndowedLog: 'Die Lateinschule trägt nun deinen Namen.', berthBuilt: 'Der Hafen hat jetzt {n} Liegeplätze.', watchEnded: 'Die Hafenwache ist wieder nüchtern und wachsam.',
    src_ventures: 'Betriebe', src_storage: 'Speichervermietung',
    ventures: 'Betriebe', vEffect_plain: 'Ein solider Betrieb mit stetigen Einnahmen.', vEffect_dive: 'Schmuggler, Hehler und Matrosen: hier wird Geld gemacht, das keiner sehen soll.', vEffect_feed: 'Versorgt die Stadt – hebt den Wohlstand und verdient in Hungersnöten doppelt.', vEffect_cooper: 'Fässer für Brauerei und Räucherei: deine Werkstätten erzeugen je 1 Last mehr.', vEffect_ships: 'Tauwerk und Segel: Reparaturen deiner Koggen werden 20 % billiger, mit beidem fahren sie einen Tag schneller.', vEffect_smoke: 'Räuchert täglich bis zu 6 Last Fisch aus deinem Lager zu Räucherfisch.', vEffect_stink: 'Stinkt zum Himmel, zahlt aber gut. Kostet täglich etwas Ruf.', vEffect_cloth: 'Gefärbtes Tuch bringt bei Schiffen und Karawanen 10 % mehr.',
    ventureBase: 'Grundeinnahmen {income} Mark/Tag', ventureInput: 'braucht {good} in der Stadt', needsCraft: 'Zunft', buyVenture: 'Betrieb kaufen ({cost} Mark)', ventureLevel: 'Ausbaustufe {level}', ventureIncome: '{income} Mark/Tag', supplyLow: '{good} ist knapp', upgradeVenture: 'Ausbauen ({cost} Mark)', sellVenture: 'Verkaufen ({price} Mark)',
    storageHint: 'Ein Speicher fasst {cap} Last. Nutze ihn selbst oder vermiete ihn an andere Kaufleute.', buyStorage: 'Speicher kaufen ({price} Mark)', storageOwn: 'als eigener Lagerplatz (+{cap} Last)', storageRent: 'vermietet: {rent} Mark/Tag', useRent: 'Vermieten', useOwn: 'Selbst nutzen', sellStorage: 'Verkaufen ({price} Mark)',
    diveHint: 'Verrufene Kaschemme am Kai. Hier verkehren Schmuggler, Hehler und Leute ohne Fragen.', diveOwned: 'Deine Spelunke bringt {income} Mark/Tag; Gerüchte sind umsonst, Schläger billiger.', contraband: 'Schwarzmarkt', contrabandOffer: 'Unter der Theke: {qty} Last {good} zu {price} Mark (sonst {base}). Ohne Zoll – aber es fällt auf.', buyContraband: 'Heimlich kaufen', contrabandNone: 'Heute liegt nichts unter der Theke. Alle drei Tage kommt neue Ware.',
    fence: 'Hehler', fenceHint: 'Der Hehler nimmt jede Ware zu 90 % des Grundpreises, ohne Marktgebühr und Absatzgrenze – heute noch {cap} Last. Jedes Geschäft weckt Verdacht.', shadyDeals: 'Krumme Dinger', bribeWatch: 'Hafenwache schmieren ({cost} Mark, {days} Tage: Schmuggel viel sicherer)', watchActive: 'Die Wache schaut noch {days} Tage weg.', hireSailors: '{ship}: Matrosen flicken den Rumpf (+25, {cost} Mark)',
    monastery: 'Kloster St. Marien', monasteryHint: 'Die Zisterzienser brauen Bier, ziehen Kerzen und schreiben ab, was in der Welt geschieht.', monkGoods: 'Klosterladen (wöchentlich)', relic: 'Reliquie stiften ({cost} Mark, +15 Frömmigkeit, +6 Ruf, einmal im Jahr)', relicDone: 'Die nächste Stiftung nimmt der Abt in {days} Tagen an.', scriptorium: 'Skriptorium: Handelsbriefe abschreiben lassen ({cost} Mark, {days} Tage): zeigt alle erwarteten Schiffe und Karawanen', scriptActive: 'Die Mönche berichten noch {days} Tage.', incomingList: 'Erwartete Ankünfte',
    hospital: 'Heilig-Geist-Spital', hospitalHint: 'Das Spital pflegt Kranke und Arme. Wohltaten hier sieht die ganze Stadt.', hospitalGiven: 'Bisher gespendet: {amount} Mark.', hospitalDonate: 'Spenden ({cost} Mark, +3 Ruf, +4 Frömmigkeit)', hospitalEndow: 'Neuen Krankensaal stiften ({cost} Mark, +12 Ruf, +8 Frömmigkeit, +5 Einfluss, +Wohlstand)', hospitalEndowed: 'Du bist Stifter des Spitals.',
    school: 'Lateinschule', schoolHint: 'Wer die Söhne der Ratsherren unterrichten lässt, hat Freunde im Rat.', schoolDonate: 'Schulgeld stiften ({cost} Mark, +5 Einfluss, +2 Ruf)', schoolCooldown: 'Die nächste Stiftung ist in {days} Tagen möglich.', schoolEndow: 'Lehrstuhl stiften ({cost} Mark, +10 Einfluss, +5 Ruf)', schoolEndowed: 'Die Schule trägt deinen Namen.',
    harbourmaster: 'Hafenmeisterei', harbourmasterHint: 'Hafenmeister Brede weist die Liegeplätze zu ({ships}/{berths} belegt) und führt das Hafenbuch.', harbourBook: 'Hafenbuch einsehen ({cost} Mark, {days} Tage): zeigt erwartete Ankünfte', harbourBookActive: 'Du darfst noch {days} Tage ins Hafenbuch schauen.', berthPriority: 'Liegezeit verlängern ({cost} Mark): alle Schiffe bleiben 2 Tage länger', extraBerth: 'Liegeplatz bauen lassen ({cost} Mark, +Ruf, +Einfluss)', berths: 'Liegeplätze',
    craftguild: 'Zunfthaus', craftHint: 'Die Handwerkerzunft entscheidet, wer in Sundhaven Bäckerei, Gerberei oder Seilerei betreiben darf. Beitritt: {fee} Mark.', joinCraft: 'Der Zunft beitreten ({fee} Mark)', craftMember: 'Zunftmitglied', apprentices: 'Lehrlinge anwerben ({cost} Mark, {days} Tage: +10 % Betriebseinnahmen)', apprenticesActive: 'Die Lehrlinge arbeiten noch {days} Tage.', masterTitle: 'Zum Ältermann ernennen lassen ({cost} Mark, drei Betriebe nötig, +8 Ruf, +6 Einfluss)', masterTitleDone: 'Ältermann der Zunft',
    fishmarket: 'Fischmarkt', fishmarketHint: 'Fischweiber verkaufen frischen und geräucherten Fisch an die Bürger – ohne Marktgebühr, heute noch {cap} Last.',
    /* Neustadt und Bollwerk */
    vEffect_caravans: 'Frische Pferde und Ställe: Karawanen bringen ein Fünftel mehr Ware und bleiben einen Tag länger.', vEffect_inn: 'Reisende zahlen gut – mehr, wenn Karawanen vor dem Tor lagern.', vEffect_gold: 'Schmuck für Patrizier: lebt vom Wohlstand der Stadt.', vEffect_plague: 'Kräuter und Tinkturen: jede zweite Pest bleibt der Stadt erspart.', vEffect_timber: 'Bauholz für die Werft: eigene Koggen werden 15 % billiger.',
    weighhouse: 'Stadtwaage', weighhouseHint: 'Jede Ware, die den Markt passiert, wird hier gewogen und mit {fee} % Marktgebühr belegt.', weighFarmHint: 'Die Waagepacht überlässt dir ein Jahr lang die Marktgebühren – derzeit etwa {income} Mark am Tag.', buyWeighFarm: 'Waagepacht erwerben ({cost} Mark)', weighFarmActive: 'Du hältst die Waagepacht noch {days} Tage ({income} Mark/Tag).', weighFarmBought: 'Du hast die Waagepacht für {days} Tage erworben.', weighFarmEnded: 'Deine Waagepacht ist abgelaufen.',
    chapel: 'Kapelle St. Gertrud', chapelHint: 'Die Schifferkapelle. Seeleute lassen hier ihre Fahrt segnen.', blessShips: 'Schiffe segnen lassen ({cost} Mark, {days} Tage: Piratengefahr halbiert)', blessingActive: 'Der Segen hält noch {days} Tage.',
    arsenal: 'Zeughaus', arsenalHint: 'Waffen und Rüstzeug der Stadt. Wer die Miliz bezahlt, dem gehört ihre Treue.', militiaHint: 'Eine Bürgermiliz hält Vitalienbrüder von Hafen und Umland fern und hebt dein Ansehen im Rat.', fundMilitia: 'Miliz aufstellen ({cost} Mark, danach {upkeep} Mark/Tag Sold)', militiaActive: 'Deine Miliz steht unter Waffen ({upkeep} Mark/Tag).', disbandMilitia: 'Miliz entlassen', militiaFunded: 'Die Bürgermiliz von Sundhaven trägt deine Farben.', plagueAverted: 'Die Apotheke hat einen Pestausbruch im Keim erstickt.',
    /* Titel, Chronik, Fraktionen */
    gameLength: 'Spieldauer', years: 'Jahre', titles: 'Titel', titlesHint: 'Sechs Wege führen zu einem Titel. Die Partie endet nach {years} Jahren am {date} mit der Chronik – wer will, spielt danach weiter.', titleHeld: 'errungen', chronicleView: 'Chronik einsehen',
    titleWonHead: 'Ein neuer Titel', titleWonHint: 'Der Titel bleibt dir. Weitere Wege stehen offen.', titleWon: 'Man nennt dich nun {title}.', endReached: 'Nach {years} Jahren wird die Chronik von Sundhaven geschlossen.',
    title_merchant_desc: 'Das Vermögen eines Fürsten, ein Monopol im Rat, Speicher am Kai und ein Umsatz, von dem die Stadt lebt.', title_mayor_desc: 'Zwei Jahre im Amt, ein treuer Rat, das Stapelrecht durchgesetzt und das Ansehen zweier Fraktionen.',
    title_shipowner_desc: 'Drei Koggen, zwanzig Fahrten, Tauwerk und Segel aus eigener Werkstatt und Erlöse, die von der Reede erzählen.', title_patron_desc: 'Frömmigkeit ohne Makel, alle Stiftungen der Kirche, eine Reliquie im Chor und ein Krankensaal mit deinem Namen.',
    title_alderman_desc: 'Ältermann der Zunft, sieben Betriebe, alle Werkstätten und die Zünfte hinter dir.', title_nightlord_desc: 'Ein Vermögen am Zoll vorbei, die Spelunke, die Hafenwache gekauft, der Vogt ein Freund – und nie verurteilt.',
    cond_worth: 'Reinvermögen {v} / {target} Mark', cond_volume: 'Handelsumsatz {v} / {target} Mark', cond_monopoly: 'Monopol im Rat gehalten', cond_storages: 'Speicher in Besitz {v} / {target}', cond_mayorYears: 'Jahre als Bürgermeister {v} / {target}', cond_loyalCouncil: 'Ratsherren mit Wohlwollen ≥ 70: {v} / {target}', cond_staple: 'Stapelrecht gilt', cond_factionsHigh: 'Fraktionen mit Ansehen ≥ 60: {v} / {target}',
    cond_ships: 'Eigene Koggen {v} / {target}', cond_voyages: 'Handelsfahrten {v} / {target}', cond_rigging: 'Seilerei und Segelmacherei {v} / {target}', cond_expedition: 'Erlös aus Fahrten {v} / {target} Mark', cond_piety: 'Frömmigkeit {v} / {target}', cond_churchProjects: 'Kirchenstiftungen {v} / {target}', cond_relic: 'Reliquie gestiftet', cond_hospital: 'Krankensaal gestiftet',
    cond_master: 'Ältermann der Zunft', cond_ventures: 'Betriebe {v} / {target}', cond_workshops: 'Werkstätten {v} / {target}', cond_guildRep: 'Ansehen bei den Zünften {v} / {target}', cond_smuggled: 'Am Zoll vorbei {v} / {target} Mark', cond_dive: 'Spelunke in Besitz', cond_watch: 'Hafenwache geschmiert {v} / {target}', cond_bailiff: 'Wohlwollen des Vogts {v} / {target}', cond_noTrial: 'Nie verurteilt',
    factionsTitle: 'Ansehen bei den Fraktionen', factionsHint: 'Patrizier, Kaufleute, Zünfte und Kirche urteilen jeder für sich. Wahlen brauchen die Fraktionen, Geschenke werden billiger, wo man dich schätzt, und jedes Gesetz verschiebt Ansehen.', electionLostFactions: 'Die Wahl ging verloren: zu wenige Fraktionen stehen hinter dir.',
    chronicleTitle: 'Chronik von Sundhaven', chronicleEnded: 'Nach {years} Jahren schließt der Chronist das Buch über {name}.', chronicleSoFar: 'Was der Chronist über {name} nach {years} Jahren notiert hat.', holdings: 'Besitz', holdingsText: '{houses} Häuser, {workshops} Werkstätten, {ventures} Betriebe, {storages} Speicher, {ships} Schiffe', rivalsBeaten: 'Überflügelte Konkurrenten', epitaph: 'Nachruf:', continueAnyway: 'Trotzdem weiterspielen',
    ep_manyTitles: '{name} trug mehr Titel, als ein Grabstein fasst.', ep_merchant: 'Sundhavens Handel trug den Namen {name}.', ep_mayor: '{name} regierte die Stadt länger, als manchem lieb war.', ep_shipowner: 'Die Flotte von {name} kannte jeden Hafen zwischen London und Riga.', ep_patron: 'Kein Altar in St. Nikolai ohne den Namen {name}.', ep_alderman: 'Die Zünfte nannten {name} ihren Vater.', ep_nightlord: 'Was {name} nachts trieb, wusste jeder und bewies keiner.', ep_rich: '{name} starb reich und wurde bald vergessen.', ep_modest: '{name} blieb ein kleiner Krämer mit großen Plänen.',
    ep_shady: 'Frömmigkeit war nicht die Sache dieses Kaufmanns.', ep_pious: 'Die Kirche hatte an diesem Kaufmann einen treuen Sohn.', ep_office: 'Im Rat saß man ungern neben diesem Kaufmann – und noch ungerner gegenüber.', ep_trader: 'Man traf diesen Kaufmann eher am Kai als in der Kirche.', ep_beatAll: 'Kruse, Bracht und Detmers blieben am Ende Zweite.', ep_beatSome: 'Nicht alle Rivalen ließen sich überflügeln.', ep_beatNone: 'Die Rivalen behielten das letzte Wort.',
    /* Rivalen */
    rivals: 'Rivalen', rivalsHint: 'Drei Kaufleute spielen dasselbe Spiel wie du – jeder auf seinem Weg. Ihre Haltung entscheidet, ob sie dir schaden oder helfen.', rivalsTavern: 'Hier trifft man die Konkurrenz auf ein Bier – oder heuert Leute gegen sie an.',
    path_merchant: 'Kaufmann', path_shipowner: 'Reeder', path_patron: 'Stifterin', attitude: 'Haltung zu dir', att_allied: 'verbündet', att_friendly: 'freundlich', att_neutral: 'neutral', att_cold: 'kühl', att_hostile: 'feindlich',
    rivalHoldings: '{houses} Häuser, {ventures} Betriebe, {storages} Speicher, {ships} Schiffe', meetRival: 'Auf ein Bier treffen ({cost} Mark, +Haltung)', allyRival: 'Bündnis schließen (2.000 Mark, Haltung ≥ 45)', rivalMetRecently: 'Ihr habt euch erst kürzlich getroffen.', rivalNotReady: 'Dafür ist die Haltung noch zu kühl.',
    ownedByRival: 'Im Besitz von {rival}.', rivalSells: 'Zu haben für {price} Mark.', rivalWontSell: 'Verkauft nicht an dich.', monopoly: 'Monopol',
    metRival: 'Ein langer Abend mit {rival} in der Taverne.', rivalAllied: '{rival} und du seid nun verbündet: gemeinsame Konvois, gemeinsame Stimmen.', allianceBroken: 'Das Bündnis mit {rival} ist zerbrochen.',
    rivalBought: '{rival} hat {thing} gekauft.', rivalShip: '{rival} hat eine Kogge bauen lassen ({n} Schiffe).', rivalSeat: '{rival} sitzt jetzt im Rat.', rivalMotionPassed: '{rival} hat im Rat durchgesetzt: {law} → {value} ({yes}:{no}).', rivalMotionFailed: 'Antrag von {rival} abgelehnt: {law} → {value} ({yes}:{no}).',
    rivalDenounce: '{rival} hat dich beim Vogt angeschwärzt.', rivalUndercut: '{rival} wirft {good} zu Schleuderpreisen auf den Markt.', rivalPoach: '{rival} hat dir den Meister der {venture} abgeworben.', rivalArson: 'Ein Brand in deinem Lager – man munkelt, {rival} stecke dahinter.',
    rivalTip: '{rival} steckt dir, welches Schiff als Nächstes einläuft.', rivalWord: '{rival} legt im Rat ein gutes Wort für dich ein.', brotherhoodFounded: '{rival} gründet die Marienbruderschaft – die Kirche hat eine neue Lieblingstochter.',
    /* Aufträge */
    contracts: 'Aufträge', contractsHint: 'Rat, Gilde, Kloster, Spelunke und Hafenmeister hängen befristete Aufträge aus. Höchstens drei zugleich; wer die Frist reißt, zahlt und verliert Ansehen.', noContracts: 'Zurzeit liegt kein Auftrag aus.',
    giver_council: 'Der Rat', giver_guild: 'Die Gilde', giver_abbey: 'Das Kloster', giver_dive: 'Ein Mann ohne Namen', giver_harbourmaster: 'Der Hafenmeister', shady: 'ohne Fragen',
    contractDeliver: 'Liefere {qty} Last {good} zu {price} Mark/Last (Grundpreis {base})', contractVoyage: 'Schicke eine Kogge nach {dest} und zurück', contractDays: 'Frist {days} Tage nach Annahme · Angebot gilt noch {left} Tage', contractDue: 'noch {days} Tage', reward: 'Lohn',
    accept: 'Annehmen', deliver: 'Liefern', contractShipUnderway: 'Schiff unterwegs', contractSendShip: 'Kogge auf Fahrt schicken', tooManyContracts: 'Mehr als drei Aufträge zugleich kannst du nicht erfüllen.',
    contractAccepted: 'Auftrag angenommen: {giver}.', contractDone: 'Auftrag für {giver} erfüllt: {reward} Mark.', contractFailed: 'Auftrag für {giver} verfehlt: {penalty} Mark Strafe, Ansehen verloren.', contractCaught: 'Die Lieferung ohne Fragen ist aufgeflogen: {fine} Mark Strafe.', contractPaid: '{reward} Mark Auftragslohn erhalten.', src_contracts: 'Aufträge',
    /* Ereignisketten */
    openDecision: 'Entscheidung treffen', needShipInPort: 'Dafür muss eine eigene Kogge im Hafen liegen.',
    chainName_vitalien: 'Die Vitalienbrüder', chainName_plague: 'Das Pestjahr', chainStart_vitalien: 'Fischer berichten von fremden Segeln vor der Küste – die Vitalienbrüder sind zurück.', chainStart_plague: 'Die ersten Toten liegen in der Neustadt. Das Pestjahr beginnt.',
    stage_vitalien_rumor: 'Gerüchte', stage_vitalien_offer: 'Ein Angebot', stage_vitalien_raid: 'Überfall', stage_vitalien_council: 'Der Rat berät', stage_vitalien_hunt: 'Kaperfahrt', stage_vitalien_peace: 'Frieden',
    stage_plague_cases: 'Erste Fälle', stage_plague_hospital: 'Das Spital ruft', stage_plague_closed: 'Hafen gesperrt', stage_plague_procession: 'Prozession', stage_plague_waiting: 'Warten', stage_plague_aftermath: 'Danach',
    dec_vitalien_offer: 'In der Spelunke setzt sich ein Fremder mit Salz im Bart zu dir. „{qty} Last {good}, {price} Mark die Last – der halbe Preis. Niemand fragt, woher sie stammen. Oder du gehst zum Rat und erzählst, dass die Vitalienbrüder vor Sundhaven ankern.“',
    ch_vitalien_offer_buy: 'Die Ware kaufen ({cost} Mark)', chh_vitalien_offer_buy: 'Billige Ware, Verdacht wächst, Bracht wird freundlicher, die Kaufleute weniger.', ch_vitalien_offer_report: 'Den Rat alarmieren', chh_vitalien_offer_report: 'Ruf und Einfluss, Patrizier zufrieden, die Stadt ist gewarnt – Bracht vergisst das nicht.', ch_vitalien_offer_ignore: 'Nichts gehört, nichts gesehen', chh_vitalien_offer_ignore: 'Kein Gewinn, kein Risiko.',
    vt_raid: 'Die Vitalienbrüder überfallen den Hafen! Ein Schiff flieht, Speicher brennen.', vt_raidWarned: 'Die Vitalienbrüder greifen an, doch die gewarnte Stadt hält den Schaden klein.', vt_raidRepelled: 'Deine Miliz schlägt die Vitalienbrüder am Bollwerk zurück.',
    dec_vitalien_council: 'Der Rat beschließt eine Kaperfahrt gegen die Vitalienbrüder. Man erwartet, dass die Kaufleute der Stadt sich beteiligen.',
    ch_vitalien_council_fund: 'Die Flotte ausrüsten (2.000 Mark)', chh_vitalien_council_fund: 'Ansehen bei den Patriziern, bessere Aussichten für die Fahrt.', ch_vitalien_council_lead: 'Mit eigener Kogge anführen', chh_vitalien_council_lead: 'Zwölf Tage Fahrt. Sieg bringt Beute, Ruf und Einfluss – Niederlage kostet den Rumpf. Eine Kogge muss im Hafen liegen.', ch_vitalien_council_stayout: 'Sich heraushalten', chh_vitalien_council_stayout: 'Die Patrizier merken es sich.',
    vt_victory: 'Sieg über die Vitalienbrüder! Deine Kogge kehrt mit {loot} Mark Beute und Ruhm zurück.', vt_defeat: 'Die Kaperfahrt endet im Chaos – deine Kogge kommt zerschossen zurück.', vt_fleetWon: 'Die Kaperflotte der Stadt hat die Vitalienbrüder vertrieben.', vt_fleetLost: 'Die Kaperflotte kehrt ohne Erfolg zurück; die Piraten ziehen von selbst weiter.', vt_peace: 'Die Vitalienbrüder verschwinden so plötzlich, wie sie kamen.',
    chain_vitalien_offer_buy: 'Du hast Hehlerware von den Vitalienbrüdern gekauft.', chain_vitalien_offer_report: 'Du hast den Rat vor den Vitalienbrüdern gewarnt.', chain_vitalien_offer_ignore: 'Du hast das Angebot der Vitalienbrüder ausgeschlagen.', chain_vitalien_council_fund: 'Du hast die Kaperflotte ausgerüstet.', chain_vitalien_council_lead: 'Du führst die Kaperfahrt an.', chain_vitalien_council_stayout: 'Du hältst dich aus der Kaperfahrt heraus.',
    dec_plague_hospital: 'Das Heilig-Geist-Spital ist überfüllt. Die Spitalmeisterin bittet die Kaufleute der Stadt um Geld für Betten, Stroh und Totengräber.',
    ch_plague_hospital_donate: 'Spenden (1.500 Mark)', chh_plague_hospital_donate: 'Kirche und Zünfte danken es, die Seuche klingt früher ab.', ch_plague_hospital_refuse: 'Ablehnen', chh_plague_hospital_refuse: 'Man wird sich erinnern, wer die Tür geschlossen hielt.',
    pl_closed: 'Der Rat sperrt den Hafen: zehn Tage lang läuft kein Schiff ein, die Kaufleute murren.',
    dec_plague_procession: 'Die Kirche ruft zur Bußprozession über den Markt. Die Reichen packen unterdessen die Wagen – wer bleibt, riskiert die Krankheit, wer geht, seinen Ruf.',
    ch_plague_procession_join: 'Mitgehen und spenden (500 Mark)', chh_plague_procession_join: 'Frömmigkeit und Kirche, die Pest klingt schneller ab.', ch_plague_procession_flee: 'Aufs Land fliehen', chh_plague_procession_flee: 'Sicher, aber Ruf und Ansehen leiden, und das Lager bleibt unbewacht.', ch_plague_procession_stay: 'Bleiben und Geschäfte machen', chh_plague_procession_stay: 'Wer bleibt, verdient – und kann selbst erkranken.',
    pl_sick: 'Das Fieber hat auch dich erwischt. Bader und Apotheke kosten 800 Mark.', pl_aftermath: 'Die Pest ist vorüber. Arbeitskräfte fehlen, Löhne steigen für 60 Tage, Häuser sind billig zu haben.',
    chain_plague_hospital_donate: 'Du hast dem Spital 1.500 Mark gespendet.', chain_plague_hospital_refuse: 'Du hast dem Spital die Hilfe verweigert.', chain_plague_procession_join: 'Du bist in der Bußprozession mitgegangen.', chain_plague_procession_flee: 'Du bist vor der Pest aufs Land geflohen.', chain_plague_procession_stay: 'Du bist in der Stadt geblieben.',
    helpTitle: 'Wie man Herr von Sundhaven wird',
    helpText: `<p><b>Das Spiel:</b> Du bist Kaufmann in Sundhaven. Klicke auf Gebäude, Schiffe, Karawanen und Passanten, um zu handeln, zu verhandeln und zu intrigieren. Die Zeit läuft in Tagen; mit den Knöpfen oben regelst du das Tempo.</p>
<p><b>Handel:</b> Schiffe und Karawanen bringen Waren billig und suchen andere teuer. Kaufe ihre Ware, verkaufe sie auf dem Markt an die Bürger – oder liefere Marktware an die Schiffe. Der Zoll frisst einen Teil; ein wohlgesonnener Zöllner oder nächtlicher Schmuggel hilft.</p>
<p><b>Geld verdienen:</b> Handel, eigene Kogge auf Fahrt, Werkstätten (Gildelizenz nötig), Mietshäuser, Marktstände, Fischerboote, Geldverleih, Taverne, Badehaus, Zollpacht, Ämter, Würfelspiel und Lieferungen an die Kirche.</p>
<p><b>Macht:</b> Im Rathaus sitzen sechs Ratsherren. Geschenke heben ihr Wohlwollen, Einfluss stellt Anträge zu Zoll, Marktgebühr, Wucherverbot, Stapelrecht, Badehausverbot und Monopolen. Mit Ruf und Freunden im Rat wirst du Ratsherr und Bürgermeister.</p>
<p><b>Kirche:</b> Spenden, Stiftungen und Lieferungen heben deine Frömmigkeit. Der Pfarrer predigt für dich – oder gegen deine Konkurrenten. Ablässe tilgen Verdacht.</p>
<p><b>Neue Viertel:</b> Am Südkai liegen Lagerhallen (kaufen, selbst nutzen oder vermieten), Fischmarkt, Spelunke (Schwarzmarkt, Hehler, bestochene Hafenwache) und Handwerker. Im Osten entscheidet die Zunft, wer Bäckerei, Böttcherei, Gerberei, Färberei, Seilerei oder Segelmacherei betreiben darf – jeder Betrieb bringt Tageseinnahmen und Nebenwirkungen. Kloster, Spital und Lateinschule belohnen Stiftungen mit Frömmigkeit, Ruf und Einfluss; der Hafenmeister führt das Hafenbuch.</p>
<p><b>Karte:</b> Mausrad oder zwei Finger zoomen, Ziehen verschiebt den Ausschnitt, Doppelklick springt heran. Tasten: + − 0 und Pfeiltasten.</p>
<p><b>Verdacht:</b> Bestechung, Schmuggel, Wucher und Schläger fallen auf. Ab 50 ermittelt der Vogt, ab 85 gibt es einen Prozess. Der Vogt lässt sich bestechen – meistens.</p>
<p><b>Ziel:</b> Bürgermeister werden, 500.000 Mark Reinvermögen und reicher als alle Konkurrenten. Bankrott nach 60 Tagen mit leerer Kasse.</p>`,
  },
  en: {
    title: 'Hanse-Kontor', subtitle: 'Sundhaven, anno 1372. A small Hanseatic town, a harbour, and your road to power.',
    newGame: 'New game', continueGame: 'Continue', continuePlay: 'Keep playing', save: 'Save', load: 'Load', exportSave: 'Export', importSave: 'Import',
    help: 'Help', saved: 'Game saved.', loaded: 'Game loaded.', noSave: 'No saved game found.', importError: 'The file could not be read.',
    confirmNewGame: 'Discard the current game and start over?', playerName: 'Your name', difficulty: 'Difficulty', easy: 'Easy', normal: 'Normal', hard: 'Hard', defaultName: 'Hinrich Castorp',
    diffHint_easy: '12,000 marks, calm times, many ships.', diffHint_normal: '6,000 marks.', diffHint_hard: '3,000 marks, rough times, few ships.',
    day: 'Day', money: 'Cash', rank: 'Rank', pause: 'Pause', speed1: 'Slow', speed2: 'Normal', speed3: 'Fast', stepDay: 'Advance one day', mark: 'marks', unitLast: 'lasts',
    rep: 'Reputation', influence: 'Influence', piety: 'Piety', suspicion: 'Suspicion', prosperity: 'Prosperity', population: 'Population', netWorth: 'Net worth',
    tabOverview: 'Overview', tabLog: 'Chronicle', tabHelp: 'Help', back: 'Back', close: 'Close', cancel: 'Cancel', ok: 'OK', yes: 'Yes', no: 'No', none: 'none',
    shortage: 'shortage', surplus: 'surplus', normalDemand: 'covered', good: 'Good', qty: 'Quantity', price: 'Price', stock: 'Stock', buy: 'Buy', sell: 'Sell', max: 'Max',
    warehouse: 'Warehouse', warehouseCap: 'Storage', capacityHint: '{used} / {cap} lasts', expandWarehouse: 'Expand warehouse (+{qty} lasts, {cost} marks)', empty: 'empty',
    notEnoughStock: 'Not enough stock.', warehouseFull: 'The warehouse is full.', notEnoughMoney: 'Not enough money.', notWanted: 'They do not want that much.', notEnoughCargo: 'Not enough in the warehouse.',
    monopolyBlocked: 'A rival holds the monopoly on this good.', marketSaturated: 'The townspeople will not take more today.', marketCapHint: 'today', pietyTooLow: 'The church only deals with pious merchants (piety 40).', needLoyalty: 'He would need to like you more for that.',
    needInfluence: 'You need 20 influence for a motion.', needRep: 'Your reputation is not high enough.', needGuild: 'Only guild members receive licences.', needLicense: 'You lack the guild licence.',
    loanTooHigh: 'Your credit limit is insufficient.', maxShips: 'The harbour cannot hold more than three of your ships.', shipDamaged: 'The ship must be repaired first.', shipFull: 'The ship is full (120 lasts).',
    harbour: 'Harbour', shipsInPort: 'Ships in port', noShips: 'No foreign ship is in port right now.', fromOrigin: 'from {origin}', captain: 'Captain', leavesIn: 'leaves in {days} days',
    offers: 'Offers', wants: 'Wants', tariffInfo: 'Tariff: {rate} % (your discount through the customs officer: {disc} %)', smuggle: 'Smuggle at night (no tariff)', smuggleHint: 'No tariff, but the customs officer might catch you.',
    bought: 'Bought {qty} lasts of {good} for {cost} marks.', sold: 'Sold {qty} lasts of {good} for {cost} marks.', smuggledOk: 'Smuggled, saved {saved} marks of duty.',
    ownShips: 'Your ships', noOwnShips: 'You own no ship. The shipyard will build one.', inPort: 'in port', away: 'bound for {dest}, back in {days} days', cargo: 'Cargo',
    loadShip: 'Load', unloadShip: 'Unload', sendShip: 'Send on voyage', destination: 'Destination', bringBack: 'Return cargo', expeditionHint: 'The ship sells its cargo at the destination (wanted goods fetch up to 1.5× base price) and buys the return cargo cheaply with the proceeds.',
    daysTrip: '{days} days round trip', repairShip: 'Repair ({cost} marks)', sellShip: 'Sell ({price} marks)', hull: 'Condition',
    market: 'Market square', marketHint: 'Sell to the townspeople here and buy what the town produces. They only take limited quantities per day; market stalls raise volume and price. Market fee: {fee} %.', stalls: 'Market stalls', buyStall: 'Lease a stall ({cost} marks, +4 % price, +50 % volume)',
    monopolyYours: 'You hold the monopoly on {good} (+35 % price).', demand: 'Demand', buyPrice: 'Buy', sellPrice: 'Sell',
    kontor: 'Office', ledger: 'Ledger (last 30 days)', income: 'Income', expenses: 'Expenses', balance: 'Balance', assets: 'Assets',
    src_shipTrade: 'Ship & caravan trade', src_market: 'Market trade', src_tariffs: 'Tariffs', src_rent: 'Rent', src_tavern: 'Tavern', src_bathhouse: 'Bathhouse', src_lending: 'Money lending', src_expedition: 'Trading voyages',
    src_taxFarm: 'Tax farm', src_office: 'Office', src_gambling: 'Gambling', src_church: 'Church & alms', src_wages: 'Wages', src_interest: 'Interest', src_bribes: 'Gifts & bribes', src_fines: 'Fines',
    src_investments: 'Purchases & building', src_politics: 'Politics', src_loans: 'Loans',
    townhall: 'Town hall', council: 'The council', yourSeat: 'Your seat', seat_none: 'no seat', seat_councillor: 'Councillor', seat_mayor: 'Mayor', loyalty: 'Goodwill', faction: 'Faction',
    giveGift: 'Gift ({cost} marks)', giftDone: '{name} accepts your gift graciously.', laws: 'Laws', current: 'currently', propose: 'Propose motion (20 influence)',
    motionPassed: 'Motion passed: {law} → {value} ({yes}:{no}).', motionFailed: 'Motion rejected: {law} → {value} ({yes}:{no}).', lawHint_tariff: 'A low tariff makes your ship trade cheaper; a high one fills the tax farm.',
    lawHint_marketFee: 'Deducted from every market sale.', lawHint_usuryBan: 'Money lending becomes suspicious while the ban is in force.', lawHint_staple: 'More ships call at the harbour.',
    lawHint_bathBan: 'Closes the bathhouse.', lawHint_monopoly: 'Only the monopoly holder may sell this good – at a premium.',
    runCouncillor: 'Run for a council seat (3,000 marks, reputation 35, three friendly councillors)', runMayor: 'Run for mayor (6,000 marks, reputation 55, four friendly councillors)',
    becameCouncillor: 'You now sit on the council of Sundhaven.', becameMayor: 'You are Mayor of Sundhaven!', electionLost: 'You lost the vote: only {support} of {need} councillors backed you.',
    acceptBribes: 'Accept bribes as office holder (+money, +suspicion)', projects: 'Town projects', fund: 'Fund ({cost} marks)', funded: 'funded', projectDone: '{project} completed.',
    taxFarm: 'Tax farm', taxFarmHint: 'Buy the right to collect all harbour tariffs for one year.', buyTaxFarm: 'Buy tax farm ({cost} marks)', taxFarmActive: 'You hold the tax farm for {days} more days.',
    taxFarmBought: 'You bought the tax farm for {days} days.', taxFarmEnded: 'Your tax farm has expired.', bathClosed: 'The bathhouse ban closes your bathhouse.',
    levy: 'The council demands a levy of {amount} marks ({days} days left).', payLevy: 'Pay levy', levyDemand: 'The council raises a special levy of {amount} marks.', levyIgnored: 'You did not pay the levy. Your reputation suffers.',
    church: 'St Nicholas Church', churchHint: 'Piety opens doors: the church buys wax and wine, the bishop praises you, and indulgences wash away suspicion.',
    donate: 'Donate', donateAmount: 'Donate {amount} marks', indulgence: 'Buy indulgence ({cost} marks, −20 suspicion)', churchSupply: 'The church needs this week', supply: 'Deliver ({qty} lasts, {price} marks/last)',
    churchProjects: 'Endowments', sermonFavor: 'Sermon in your favour (500 marks, +8 reputation)', sermonAgainst: 'Sermon against a rival (800 marks)',
    sermonAgainstLog: 'Father Anselm preaches against {rival}.', bishopPleased: 'The bishop visits Sundhaven and praises your piety.', bishopDispleased: 'The bishop visits Sundhaven and rebukes your way of life.',
    customs: 'Customs house', customsHint: 'Customs officer {name} levies {rate} % on imports and half of that on exports. The more he likes you, the more he looks away (currently {disc} % discount).',
    smuggleStats: 'Smuggled past customs so far: {amount} marks.', smuggleCaught: 'Caught smuggling! Fine: {fine} marks.',
    guild: 'Guild hall', guildHint: 'The guild grants workshop licences. Membership: {fee} marks.', joinGuild: 'Join the guild ({fee} marks)', member: 'Member', licenses: 'Licences', buyLicense: 'Licence ({cost} marks)', licensed: 'licensed',
    workshop: 'Workshop', workshopEmpty: 'Empty plot. With a guild licence you can build a workshop here.', build: 'Build ({cost} marks)', produces: 'produces {qty} lasts of {good}/day', consumes: 'consumes {inp}',
    wage: 'Wages {wage} marks/day', idle: 'idle – inputs missing in warehouse', running: 'running', demolish: 'Demolish', workshopBuilt: '{workshop} built.',
    house: 'House', houseOwnerNpc: 'Owned by a citizen. Price: {price} marks.', buyHouse: 'Buy ({price} marks)', rentPerDay: 'Rent {rent} marks/day', level: 'Level {level}',
    upgradeHouse: 'Upgrade ({cost} marks, +12 marks/day)', sellHouse: 'Sell ({price} marks)', damaged: 'Fire damage – no rent', repairHouse: 'Repair (800 marks)', yours: 'Yours',
    tavern: 'The Golden Herring Tavern', tavernHint: 'Rumours, dice, and people who will do anything for money.', rumor: 'Buy a rumour ({cost} marks)', rumors: 'Word on the street',
    rumorShip: 'A ship from {origin} is said to arrive in {days} days, carrying {goods}.', rumorCaravan: 'A caravan from {origin} is expected in {days} days, with {goods}.', rumorNothing: 'Nothing new – only gossip about the mayor.',
    gamble: 'Roll dice', bet: 'Stake', gambleWon: 'You won! {bet} marks gained.', gambleLost: 'You lost {bet} marks.', hire: 'Hire', hireSpy: 'Spy (600 marks, 60 days): reveals the true goodwill of the council',
    spyActive: 'Your spy reports for {days} more days.', hireThugsCollect: 'Thugs: collect from a defaulting debtor (900 marks)', hireThugsSabotage: 'Thugs: harm {rival} (900 marks)',
    thugsCollected: 'The thugs collected {amount} marks from {name}.', thugsFailed: '{name} has gone into hiding – the thugs came back empty-handed.', thugsNothing: 'There is no defaulting debtor.',
    sabotageOk: 'A warehouse fire has hit {rival} hard.', sabotageFailed: 'The thugs were caught and gave you away – {rival} knows.',
    buyTavern: 'Buy the tavern ({cost} marks)', tavernOwned: 'Your tavern earns {income} marks/day (more when ships are in port).',
    bank: 'Money changer', yourLoan: 'Your loan', loanLimit: 'Credit limit', takeLoan: 'Borrow', repay: 'Repay', interestInfo: 'Interest {pct} % per year',
    lending: 'Lend money', lendingHint: 'Citizens seek credit. High interest means high risk. Under a usury ban every loan makes you suspicious.', lend: 'Lend',
    borrower: 'Borrower', interest: 'Interest', term: 'Term {days} days', risk: 'Risk', risk_low: 'low', risk_mid: 'medium', risk_high: 'high', outstanding: 'Outstanding loans', dueIn: 'due in {days} days',
    defaulted: 'in default', loanDefault: '{name} cannot repay {amount} marks.', loanRepaid: '{name} repays {amount} marks.', usuryWarning: 'Usury ban in force!',
    bailiff: "Bailiff's court", bailiffHint: 'Bailiff {name} keeps law and order. At high suspicion he investigates; at 85 you stand trial.', noInvestigation: 'There is nothing against you.',
    investigation: 'The bailiff is investigating you – {days} days until the verdict.', bribeBailiff: 'Bribe the bailiff ({cost} marks)', investigationOpened: 'The bailiff has opened an investigation against you.',
    investigationDropped: 'The investigation has been dropped.', bribeRefused: 'The bailiff refuses your money – and remembers it.', investigationFine: 'The bailiff fines you {fine} marks.',
    trial: 'Trial before the council! {fine} marks fine, offices lost, reputation ruined.',
    shipyard: 'Shipyard', shipyardHint: 'Shipwright {name} builds cogs for trading voyages and fishing boats.', buyShip: 'Build a cog ({cost} marks, 120 lasts)', buyBoat: 'Fishing boat ({cost} marks, {fish} fish/day)', boats: 'Fishing boats',
    fishermen: "Fishermen's huts", fishermenHint: 'The fishermen sell their catch cheaply straight from the pier. Today: {qty} lasts at {price} marks.', buyFish: 'Buy fish',
    gate: 'Town gate', gateHint: 'Caravans from the overland road camp outside the gate.', caravans: 'Caravans', noCaravans: 'Nobody is camped outside the gate right now.', caravanFrom: 'Caravan from {origin}',
    shipArrived: '{ship} from {origin} has arrived.', caravanArrived: 'A caravan from {origin} has reached the gate.', shipLeftNoBerth: 'A ship from {origin} found no berth and sailed on.',
    ev_famine: 'Famine in Sundhaven! Grain and fish are in demand.', ev_plague: 'The plague is in town. The streets empty.', ev_goodCatch: 'A rich catch! Fish is cheap.', ev_fair: 'Fair in Sundhaven – cloth, furs and spices in demand.',
    evn_famine: 'Famine', evn_plague: 'Plague', evn_goodCatch: 'Rich catch', evn_fair: 'Fair', fireHouse: 'Fire! {house} has burnt out.', fireWarehouse: 'Fire in the harbour quarter – a tenth of your stock has burnt.',
    piratesRepelled: 'Victual Brothers off the coast! The town wall keeps them away.', piratesRaid: 'Victual Brothers raid the harbour! Ships flee, warehouses burn.', stormEvent: 'Heavy storm at sea. Ships are delayed.',
    expeditionPirates: '{ship} was robbed by pirates.', shipSent: '{ship} sails for {dest}.', shipReturned: '{ship} is back: {revenue} marks earned, return cargo {cargo}.',
    season_lent: 'Lent', season_easter: 'Easter', season_midsummer: 'Midsummer', season_michaelmas: 'Michaelmas', season_christmas: 'Christmas',
    promoted: 'People now call you {rank}.', won: 'You are Mayor, the richest citizen and Lord of Sundhaven!', bankrupt: 'You are bankrupt. Your creditors seize your office.', gameOver: 'Game over',
    welcome: 'Welcome to Sundhaven, {name}! Two ships are in port and a caravan waits at the gate. Click on buildings and people.',
    encBeggar: 'A beggar holds out his hand. "Alms, sir, for the love of God."', encMonk: 'A mendicant monk asks for a gift for the monastery.', alms: 'Give ({cost} marks)',
    encMerchantTip: 'A merchant whispers: "{good}? There is a {label} at the market."', encMerchant: 'A merchant nods curtly and hurries to the harbour.', encFisher: 'A fisherman offers you 10 lasts of fish under the counter.', cheapFish: 'Take it ({cost} marks)',
    encFisherTalk: 'A fisherman complains about the Victual Brothers and the price of salt.', encGuard: 'The town guard nods at you.', encGuardSuspicious: 'The guard studies you for a long moment. People are talking about you.', encChild: 'Children play tag and nearly run into you.',
    encGossip: 'A townswoman whispers: councillor {name} is {loyalty} towards you.', gossipFriendly: 'well disposed', gossipCold: 'cold', encCitizenRep: 'A citizen greets you. Your reputation in town stands at {rep}.', encCitizen: 'A citizen wishes you a good day.', bathhouse: 'Bathhouse', buyBathhouse: 'Buy the bathhouse ({cost} marks)', leader: 'Caravan leader', movesOn: 'moves on in {days} days',
    enc_citizen_label: 'Citizen', enc_merchant_label: 'Merchant', enc_fisher_label: 'Fisherman', enc_beggar_label: 'Beggar', enc_monk_label: 'Monk', enc_guard_label: 'Town guard', enc_child_label: 'Children',
    overview: 'Overview', goals: 'Six paths, six titles: merchant prince, mayor, shipowner, patron, alderman or lord of the night. At the end of the game the chronicler writes your account.', richest: 'Richest in town', you: 'you', incomeSources: 'Your income sources',
    dailyIncome: 'Avg. daily income', chart: 'Net worth over time', noLog: 'Nothing has happened yet.', activeEvents: 'Currently in town', personsTitle: 'Important people',
    legend: 'Click on buildings, ships, caravans and passers-by. Scroll to zoom, drag to move the map.', timeOfDay: 'Time of day', night: 'Night', morning: 'Morning', noon: 'Noon', evening: 'Evening',
    /* New quarters */
    needCraftGuild: 'You must be a member of the craft guild.', needThreeVentures: 'The title requires three businesses of your own.', storageInUse: 'The store is still in use – empty your warehouse first.', fenceFull: 'The fence takes no more today.', noShipsHere: 'No foreign ship is in port.',
    craftJoined: 'The craft guild has admitted you.', ventureBought: '{venture} is now yours.', masterTitleLog: 'The guild names you alderman.', relicDonated: 'The abbey enshrines your relic. All of Sundhaven comes to pray.', hospitalEndowedLog: 'You are patron of the Holy Ghost hospital.', schoolEndowedLog: 'The Latin school now bears your name.', berthBuilt: 'The harbour now has {n} berths.', watchEnded: 'The harbour watch is sober and alert again.',
    src_ventures: 'Businesses', src_storage: 'Storage rent',
    ventures: 'Businesses', vEffect_plain: 'A solid business with steady income.', vEffect_dive: 'Smugglers, fences and sailors: money is made here that nobody should see.', vEffect_feed: 'Feeds the town – raises prosperity and earns double during famines.', vEffect_cooper: 'Barrels for brewery and smokehouse: your workshops produce 1 last more each.', vEffect_ships: 'Rope and sails: repairs of your cogs are 20 % cheaper; with both, voyages take a day less.', vEffect_smoke: 'Smokes up to 6 lasts of fish from your warehouse per day.', vEffect_stink: 'Stinks to high heaven but pays well. Costs a little reputation daily.', vEffect_cloth: 'Dyed cloth fetches 10 % more from ships and caravans.',
    ventureBase: 'Base income {income} marks/day', ventureInput: 'needs {good} in town', needsCraft: 'guild', buyVenture: 'Buy business ({cost} marks)', ventureLevel: 'Level {level}', ventureIncome: '{income} marks/day', supplyLow: '{good} is scarce', upgradeVenture: 'Expand ({cost} marks)', sellVenture: 'Sell ({price} marks)',
    storageHint: 'A store holds {cap} lasts. Use it yourself or rent it to other merchants.', buyStorage: 'Buy store ({price} marks)', storageOwn: 'used as your own storage (+{cap} lasts)', storageRent: 'rented out: {rent} marks/day', useRent: 'Rent out', useOwn: 'Use yourself', sellStorage: 'Sell ({price} marks)',
    diveHint: 'A disreputable dive on the quay, frequented by smugglers, fences and people who ask no questions.', diveOwned: 'Your dive earns {income} marks/day; rumours are free and thugs cheaper.', contraband: 'Black market', contrabandOffer: 'Under the counter: {qty} lasts of {good} at {price} marks (normally {base}). Duty-free – but noticed.', buyContraband: 'Buy quietly', contrabandNone: 'Nothing under the counter today. New goods arrive every three days.',
    fence: 'Fence', fenceHint: 'The fence takes any goods at 90 % of base price, without market fee or sales limit – {cap} lasts left today. Every deal raises suspicion.', shadyDeals: 'Shady dealings', bribeWatch: 'Bribe the harbour watch ({cost} marks, {days} days: smuggling much safer)', watchActive: 'The watch looks away for {days} more days.', hireSailors: '{ship}: sailors patch the hull (+25, {cost} marks)',
    monastery: "St Mary's Abbey", monasteryHint: 'The Cistercians brew beer, make candles and copy down whatever happens in the world.', monkGoods: 'Abbey shop (weekly)', relic: 'Donate a relic ({cost} marks, +15 piety, +6 reputation, once a year)', relicDone: 'The abbot accepts the next donation in {days} days.', scriptorium: 'Scriptorium: copy trade letters ({cost} marks, {days} days): shows all expected ships and caravans', scriptActive: 'The monks report for {days} more days.', incomingList: 'Expected arrivals',
    hospital: 'Holy Ghost hospital', hospitalHint: 'The hospital cares for the sick and poor. Good deeds here are seen by the whole town.', hospitalGiven: 'Donated so far: {amount} marks.', hospitalDonate: 'Donate ({cost} marks, +3 reputation, +4 piety)', hospitalEndow: 'Endow a new ward ({cost} marks, +12 reputation, +8 piety, +5 influence, +prosperity)', hospitalEndowed: 'You are patron of the hospital.',
    school: 'Latin school', schoolHint: "Whoever pays for the councillors' sons to be taught has friends on the council.", schoolDonate: 'Endow tuition ({cost} marks, +5 influence, +2 reputation)', schoolCooldown: 'The next endowment is possible in {days} days.', schoolEndow: 'Endow a chair ({cost} marks, +10 influence, +5 reputation)', schoolEndowed: 'The school bears your name.',
    harbourmaster: "Harbour master's office", harbourmasterHint: 'Harbour master Brede assigns berths ({ships}/{berths} occupied) and keeps the harbour book.', harbourBook: 'Consult the harbour book ({cost} marks, {days} days): shows expected arrivals', harbourBookActive: 'You may read the harbour book for {days} more days.', berthPriority: 'Extend lay days ({cost} marks): all ships stay 2 days longer', extraBerth: 'Have a berth built ({cost} marks, +reputation, +influence)', berths: 'Berths',
    craftguild: 'Craft guild hall', craftHint: 'The craft guild decides who may run a bakery, tannery or ropewalk in Sundhaven. Membership: {fee} marks.', joinCraft: 'Join the guild ({fee} marks)', craftMember: 'Guild member', apprentices: 'Recruit apprentices ({cost} marks, {days} days: +10 % business income)', apprenticesActive: 'The apprentices work for {days} more days.', masterTitle: 'Be named alderman ({cost} marks, three businesses required, +8 reputation, +6 influence)', masterTitleDone: 'Alderman of the guild',
    fishmarket: 'Fish market', fishmarketHint: 'Fishwives sell fresh and smoked fish to the townsfolk – no market fee, {cap} lasts left today.',
    /* New town and bulwark */
    vEffect_caravans: 'Fresh horses and stables: caravans bring a fifth more goods and stay a day longer.', vEffect_inn: 'Travellers pay well – more when caravans camp at the gate.', vEffect_gold: 'Jewellery for patricians: thrives on the town’s prosperity.', vEffect_plague: 'Herbs and tinctures: every second plague spares the town.', vEffect_timber: 'Timber for the shipyard: your own cogs cost 15 % less.',
    weighhouse: 'Weigh house', weighhouseHint: 'Every good passing the market is weighed here and charged the {fee} % market fee.', weighFarmHint: 'The weigh farm grants you the market fees for a year – currently about {income} marks a day.', buyWeighFarm: 'Buy the weigh farm ({cost} marks)', weighFarmActive: 'You hold the weigh farm for {days} more days ({income} marks/day).', weighFarmBought: 'You bought the weigh farm for {days} days.', weighFarmEnded: 'Your weigh farm has expired.',
    chapel: "St Gertrude's chapel", chapelHint: "The seamen's chapel. Sailors have their voyages blessed here.", blessShips: 'Have your ships blessed ({cost} marks, {days} days: pirate risk halved)', blessingActive: 'The blessing holds for {days} more days.',
    arsenal: 'Arsenal', arsenalHint: 'The town’s arms and armour. Whoever pays the militia owns its loyalty.', militiaHint: 'A citizen militia keeps the Victual Brothers away from harbour and countryside and raises your standing on the council.', fundMilitia: 'Raise a militia ({cost} marks, then {upkeep} marks/day pay)', militiaActive: 'Your militia is under arms ({upkeep} marks/day).', disbandMilitia: 'Disband militia', militiaFunded: 'The citizen militia of Sundhaven wears your colours.', plagueAverted: 'The apothecary nipped an outbreak of plague in the bud.',
    /* Titles, chronicle, factions */
    gameLength: 'Game length', years: 'years', titles: 'Titles', titlesHint: 'Six paths lead to a title. The game ends after {years} years on {date} with the chronicle – you may play on afterwards.', titleHeld: 'held', chronicleView: 'View chronicle',
    titleWonHead: 'A new title', titleWonHint: 'The title is yours to keep. Other paths remain open.', titleWon: 'People now call you {title}.', endReached: 'After {years} years the chronicle of Sundhaven is closed.',
    title_merchant_desc: 'The wealth of a prince, a monopoly on the council, stores on the quay and a turnover the town lives on.', title_mayor_desc: 'Two years in office, a loyal council, the staple right enforced and the standing of two factions.',
    title_shipowner_desc: 'Three cogs, twenty voyages, rope and sails from your own workshops and revenues the roadstead talks about.', title_patron_desc: 'Piety without blemish, every church endowment, a relic in the choir and a ward that bears your name.',
    title_alderman_desc: 'Alderman of the guild, seven businesses, every workshop and the guilds behind you.', title_nightlord_desc: 'A fortune past the customs, the dive, the harbour watch bought, the bailiff a friend – and never convicted.',
    cond_worth: 'Net worth {v} / {target} marks', cond_volume: 'Trade turnover {v} / {target} marks', cond_monopoly: 'Monopoly held on the council', cond_storages: 'Stores owned {v} / {target}', cond_mayorYears: 'Years as mayor {v} / {target}', cond_loyalCouncil: 'Councillors with goodwill ≥ 70: {v} / {target}', cond_staple: 'Staple right in force', cond_factionsHigh: 'Factions with standing ≥ 60: {v} / {target}',
    cond_ships: 'Own cogs {v} / {target}', cond_voyages: 'Trading voyages {v} / {target}', cond_rigging: 'Ropewalk and sailmaker {v} / {target}', cond_expedition: 'Voyage revenue {v} / {target} marks', cond_piety: 'Piety {v} / {target}', cond_churchProjects: 'Church endowments {v} / {target}', cond_relic: 'Relic donated', cond_hospital: 'Ward endowed',
    cond_master: 'Alderman of the guild', cond_ventures: 'Businesses {v} / {target}', cond_workshops: 'Workshops {v} / {target}', cond_guildRep: 'Standing with the guilds {v} / {target}', cond_smuggled: 'Past the customs {v} / {target} marks', cond_dive: 'Dive owned', cond_watch: 'Harbour watch bribed {v} / {target}', cond_bailiff: "Bailiff's goodwill {v} / {target}", cond_noTrial: 'Never convicted',
    factionsTitle: 'Standing with the factions', factionsHint: 'Patricians, merchants, guilds and church each judge for themselves. Elections need the factions, gifts are cheaper where you are esteemed, and every law shifts standing.', electionLostFactions: 'The election was lost: too few factions stand behind you.',
    chronicleTitle: 'Chronicle of Sundhaven', chronicleEnded: 'After {years} years the chronicler closes the book on {name}.', chronicleSoFar: 'What the chronicler has noted about {name} after {years} years.', holdings: 'Holdings', holdingsText: '{houses} houses, {workshops} workshops, {ventures} businesses, {storages} stores, {ships} ships', rivalsBeaten: 'Rivals outdone', epitaph: 'Epitaph:', continueAnyway: 'Play on anyway',
    ep_manyTitles: '{name} bore more titles than a gravestone can hold.', ep_merchant: "Sundhaven's trade bore the name {name}.", ep_mayor: '{name} ruled the town longer than some liked.', ep_shipowner: "The fleet of {name} knew every harbour between London and Riga.", ep_patron: 'No altar in St Nicholas without the name {name}.', ep_alderman: 'The guilds called {name} their father.', ep_nightlord: 'What {name} did at night everyone knew and nobody proved.', ep_rich: '{name} died rich and was soon forgotten.', ep_modest: '{name} remained a small trader with big plans.',
    ep_shady: 'Piety was not this merchant’s concern.', ep_pious: 'The church had a faithful son in this merchant.', ep_office: 'On the council few liked to sit beside this merchant – and fewer opposite.', ep_trader: 'You met this merchant on the quay rather than in church.', ep_beatAll: 'Kruse, Bracht and Detmers ended up second.', ep_beatSome: 'Not every rival could be outdone.', ep_beatNone: 'The rivals kept the last word.',
    /* Rivals */
    rivals: 'Rivals', rivalsHint: 'Three merchants play the same game as you – each on their own path. Their attitude decides whether they harm or help you.', rivalsTavern: 'Meet the competition over a beer here – or hire people against them.',
    path_merchant: 'Merchant', path_shipowner: 'Shipowner', path_patron: 'Patroness', attitude: 'Attitude to you', att_allied: 'allied', att_friendly: 'friendly', att_neutral: 'neutral', att_cold: 'cold', att_hostile: 'hostile',
    rivalHoldings: '{houses} houses, {ventures} businesses, {storages} stores, {ships} ships', meetRival: 'Meet over a beer ({cost} marks, +attitude)', allyRival: 'Form an alliance (2,000 marks, attitude ≥ 45)', rivalMetRecently: 'You met only recently.', rivalNotReady: 'The attitude is still too cold for that.',
    ownedByRival: 'Owned by {rival}.', rivalSells: 'For sale at {price} marks.', rivalWontSell: 'Will not sell to you.', monopoly: 'Monopoly',
    metRival: 'A long evening with {rival} at the tavern.', rivalAllied: '{rival} and you are now allied: joint convoys, joint votes.', allianceBroken: 'The alliance with {rival} has broken.',
    rivalBought: '{rival} bought {thing}.', rivalShip: '{rival} had a cog built ({n} ships).', rivalSeat: '{rival} now sits on the council.', rivalMotionPassed: '{rival} carried a motion: {law} → {value} ({yes}:{no}).', rivalMotionFailed: "{rival}'s motion was rejected: {law} → {value} ({yes}:{no}).",
    rivalDenounce: '{rival} denounced you to the bailiff.', rivalUndercut: '{rival} dumps {good} on the market at rock-bottom prices.', rivalPoach: '{rival} poached the master of your {venture}.', rivalArson: 'A fire in your warehouse – rumour says {rival} is behind it.',
    rivalTip: '{rival} tips you off about the next ship to arrive.', rivalWord: '{rival} puts in a good word for you on the council.', brotherhoodFounded: "{rival} founds the Brotherhood of St Mary – the church has a new favourite daughter.",
    /* Contracts */
    contracts: 'Contracts', contractsHint: 'Council, guild, abbey, dive and harbour master post time-limited contracts. Three at most; missing a deadline costs money and standing.', noContracts: 'No contract is posted at the moment.',
    giver_council: 'The council', giver_guild: 'The guild', giver_abbey: 'The abbey', giver_dive: 'A man without a name', giver_harbourmaster: 'The harbour master', shady: 'no questions',
    contractDeliver: 'Deliver {qty} lasts of {good} at {price} marks/last (base {base})', contractVoyage: 'Send a cog to {dest} and back', contractDays: 'Deadline {days} days after acceptance · offer open {left} more days', contractDue: '{days} days left', reward: 'Reward',
    accept: 'Accept', deliver: 'Deliver', contractShipUnderway: 'Ship under way', contractSendShip: 'Send a cog on the voyage', tooManyContracts: 'You cannot handle more than three contracts at once.',
    contractAccepted: 'Contract accepted: {giver}.', contractDone: 'Contract for {giver} fulfilled: {reward} marks.', contractFailed: 'Contract for {giver} missed: {penalty} marks penalty, standing lost.', contractCaught: 'The no-questions delivery was discovered: {fine} marks fine.', contractPaid: '{reward} marks contract pay received.', src_contracts: 'Contracts',
    /* Event chains */
    openDecision: 'Make a decision', needShipInPort: 'You need one of your own cogs in port for that.',
    chainName_vitalien: 'The Victual Brothers', chainName_plague: 'The plague year', chainStart_vitalien: 'Fishermen report strange sails off the coast – the Victual Brothers are back.', chainStart_plague: 'The first dead lie in the new town. The plague year begins.',
    stage_vitalien_rumor: 'Rumours', stage_vitalien_offer: 'An offer', stage_vitalien_raid: 'Raid', stage_vitalien_council: 'The council deliberates', stage_vitalien_hunt: 'Privateering', stage_vitalien_peace: 'Peace',
    stage_plague_cases: 'First cases', stage_plague_hospital: 'The hospital calls', stage_plague_closed: 'Harbour closed', stage_plague_procession: 'Procession', stage_plague_waiting: 'Waiting', stage_plague_aftermath: 'Aftermath',
    dec_vitalien_offer: 'In the dive a stranger with salt in his beard sits down beside you. “{qty} lasts of {good}, {price} marks a last – half price. Nobody asks where it came from. Or you go to the council and tell them the Victual Brothers are anchored off Sundhaven.”',
    ch_vitalien_offer_buy: 'Buy the goods ({cost} marks)', chh_vitalien_offer_buy: 'Cheap goods, suspicion grows, Bracht warms to you, the merchants less so.', ch_vitalien_offer_report: 'Alert the council', chh_vitalien_offer_report: 'Reputation and influence, patricians pleased, the town is warned – Bracht will not forget.', ch_vitalien_offer_ignore: 'Heard nothing, seen nothing', chh_vitalien_offer_ignore: 'No gain, no risk.',
    vt_raid: 'The Victual Brothers raid the harbour! A ship flees, stores burn.', vt_raidWarned: 'The Victual Brothers attack, but the forewarned town keeps the damage small.', vt_raidRepelled: 'Your militia throws the Victual Brothers back at the bulwark.',
    dec_vitalien_council: 'The council decides on a privateering expedition against the Victual Brothers. The town’s merchants are expected to take part.',
    ch_vitalien_council_fund: 'Equip the fleet (2,000 marks)', chh_vitalien_council_fund: 'Standing with the patricians, better odds for the expedition.', ch_vitalien_council_lead: 'Lead it with your own cog', chh_vitalien_council_lead: 'Twelve days at sea. Victory brings loot, reputation and influence – defeat costs the hull. A cog must be in port.', ch_vitalien_council_stayout: 'Stay out of it', chh_vitalien_council_stayout: 'The patricians will remember.',
    vt_victory: 'Victory over the Victual Brothers! Your cog returns with {loot} marks of loot and glory.', vt_defeat: 'The expedition ends in chaos – your cog limps back shot to pieces.', vt_fleetWon: 'The town’s privateers have driven off the Victual Brothers.', vt_fleetLost: 'The privateers return empty-handed; the pirates move on by themselves.', vt_peace: 'The Victual Brothers vanish as suddenly as they came.',
    chain_vitalien_offer_buy: 'You bought stolen goods from the Victual Brothers.', chain_vitalien_offer_report: 'You warned the council about the Victual Brothers.', chain_vitalien_offer_ignore: 'You declined the Victual Brothers’ offer.', chain_vitalien_council_fund: 'You equipped the privateer fleet.', chain_vitalien_council_lead: 'You lead the privateering expedition.', chain_vitalien_council_stayout: 'You stay out of the expedition.',
    dec_plague_hospital: 'The Holy Ghost hospital is overflowing. The matron asks the town’s merchants for money for beds, straw and gravediggers.',
    ch_plague_hospital_donate: 'Donate (1,500 marks)', chh_plague_hospital_donate: 'Church and guilds are grateful; the epidemic fades sooner.', ch_plague_hospital_refuse: 'Refuse', chh_plague_hospital_refuse: 'People will remember who kept the door shut.',
    pl_closed: 'The council closes the harbour: no ship enters for ten days, the merchants grumble.',
    dec_plague_procession: 'The church calls a penitential procession across the market. Meanwhile the rich pack their wagons – whoever stays risks the sickness, whoever leaves risks their name.',
    ch_plague_procession_join: 'Join and donate (500 marks)', chh_plague_procession_join: 'Piety and church; the plague fades faster.', ch_plague_procession_flee: 'Flee to the countryside', chh_plague_procession_flee: 'Safe, but reputation and standing suffer and the warehouse is left unguarded.', ch_plague_procession_stay: 'Stay and do business', chh_plague_procession_stay: 'Those who stay earn – and may fall ill themselves.',
    pl_sick: 'The fever caught you too. Barber and apothecary cost 800 marks.', pl_aftermath: 'The plague is over. Labour is short, wages rise for 60 days, houses are cheap.',
    chain_plague_hospital_donate: 'You donated 1,500 marks to the hospital.', chain_plague_hospital_refuse: 'You refused the hospital help.', chain_plague_procession_join: 'You joined the penitential procession.', chain_plague_procession_flee: 'You fled the plague to the countryside.', chain_plague_procession_stay: 'You stayed in town.',
    helpTitle: 'How to become Lord of Sundhaven',
    helpText: `<p><b>The game:</b> You are a merchant in Sundhaven. Click on buildings, ships, caravans and passers-by to trade, negotiate and scheme. Time passes in days; the buttons at the top set the pace.</p>
<p><b>Trade:</b> Ships and caravans bring goods cheaply and pay dearly for others. Buy their cargo and sell it at the market to the townspeople – or deliver market goods to the ships. Customs takes a cut; a friendly customs officer or smuggling at night helps.</p>
<p><b>Making money:</b> trade, your own cog on voyages, workshops (guild licence required), rental houses, market stalls, fishing boats, money lending, tavern, bathhouse, tax farm, offices, dice and deliveries to the church.</p>
<p><b>Power:</b> Six councillors sit in the town hall. Gifts raise their goodwill; influence lets you table motions on tariffs, market fees, usury, staple rights, the bathhouse and monopolies. With reputation and friends on the council you become councillor and mayor.</p>
<p><b>Church:</b> Donations, endowments and deliveries raise your piety. The priest preaches for you – or against your rivals. Indulgences erase suspicion.</p>
<p><b>New quarters:</b> On the south quay are warehouses (buy, use or rent out), the fish market, the dive (black market, fence, bribed harbour watch) and craftsmen. In the east the craft guild decides who may run a bakery, cooperage, tannery, dye works, ropewalk or sailmaker – each business yields daily income and side effects. Abbey, hospital and Latin school reward endowments with piety, reputation and influence; the harbour master keeps the harbour book.</p>
<p><b>Map:</b> Scroll wheel or pinch to zoom, drag to move the view, double-click to jump in. Keys: + − 0 and the arrow keys.</p>
<p><b>Suspicion:</b> Bribery, smuggling, usury and thugs get noticed. From 50 the bailiff investigates, at 85 you stand trial. The bailiff can be bribed – usually.</p>
<p><b>Goal:</b> Become mayor, reach 500,000 marks net worth and be richer than every rival. Bankruptcy after 60 days with an empty purse.</p>`,
  },
};
HK.t = function (key, vars) {
  let s = HK.I18N[HK.LANG][key];
  if (s === undefined) s = HK.I18N.de[key];
  if (s === undefined) return key;
  if (vars) for (const k in vars) s = s.split('{' + k + '}').join(vars[k]);
  return s;
};
HK.name = obj => obj.name[HK.LANG] || obj.name.de;
HK.goodName = id => HK.name(HK.GOOD[id]);
HK.fmt = n => Math.round(n).toLocaleString(HK.LANG === 'de' ? 'de-DE' : 'en-GB');
HK.fmtDate = function (day) {
  const c = HK.CONST, base = new Date(Date.UTC(2000, c.START_MONTH, c.START_DAY));
  base.setUTCDate(base.getUTCDate() + day);
  const year = c.START_YEAR + (base.getUTCFullYear() - 2000);
  return new Intl.DateTimeFormat(HK.LANG === 'de' ? 'de-DE' : 'en-GB', { day: 'numeric', month: 'long', timeZone: 'UTC' }).format(base) + ' ' + year;
};
HK.monthOf = function (day) {
  const c = HK.CONST, base = new Date(Date.UTC(2000, c.START_MONTH, c.START_DAY));
  base.setUTCDate(base.getUTCDate() + day);
  return base.getUTCMonth();
};
